name: Blank Issue
description: A blank issue template. Useful for contacting devs.
body:
  - type: markdown
    attributes:
      value: |
        **If you have a feature request / bug report, it is better to use the appropriate issue templates instead of a blank issue. This is meant for people who would like to get in contact with the dev without using Discord.**
  - type: textarea
    attributes:
      label: "Issue"
